config/routes.rb
Rails.application.routes.draw do

  get 'statements/index'
  post 'statements/import'
  delete 'statements/destroy'
  post 'statements/upload'
  root to: 'static_pages#home'
  get 'posts/:id/download', to: 'posts#download', as: :download_image

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
end

app/models/statement.rb
class Statement < ApplicationRecord

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      record = Statement.find_by(id: row["id"]) || new
      record.update row.to_hash
      record.save!
    end
  end

  def self.to_csv
    attributes = %w{id date amount description}
    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |statement|
        csv << statement.attributes.values_at(*attributes)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :download]

  def download
    require 'open-uri'
    url =  @post.image.service_url
    data = open(url).read
    send_data data, filename: "#{params[:id]}.jpeg", disposition: 'attachment'
  end

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content, :image)
    end
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  def index
    @statements = Statement.all

    respond_to do |format|
      format.html
      format.csv { send_data @statements.to_csv, filename: "statements-#{Date.today}.csv" }
    end
  end

  def destroy
    Statement.destroy_all
    redirect_to statements_index_path
  end

  def import
    Statement.import(params[:file])
    redirect_to statements_index_path, notice: "Statement data imported!"
  end

  def upload
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Storagepractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <%= form.file_field :image %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'New Post', new_post_path %></p>
<p><%= link_to 'Statements', statements_index_path %></p>
<p><%= link_to 'Back to home', root_path %></p>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= image_tag rails_blob_path(@post.image, disposition: "attachment", only_path: true)%>
<%= link_to 'Download image', download_image_path(@post)%>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/statements/import.html.erb
<h1>Statements#import</h1>
<p>Find me in app/views/statements/import.html.erb</p>

app/views/statements/index.html.erb
<%= flash[:notice] %>

<h1>Statements</h1>

<h2>Note</h2>
<p>CSV should be imported with the following format: id,date,amount,description. In case you don't add an ID, it will
directly create new entries for the CSV</p>

<p>
  Download:
  <%=link_to 'CSV', statements_index_path(format: 'csv') %>
</p>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Amount</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <% @statements.each do |statement| %>
      <tr>
        <td><%= statement.date %></td>
        <td><%= statement.amount %></td>
        <td><%= statement.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Import statement data!</h3>
  <%= form_with url: statements_import_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
  <% end %>

<!--TODO New bucket for CSV's, other one for images, since it can't be separated.-->
<!--TODO Read from files from the bucket-->

<h3>Upload statements to bucket</h3>
  <%= form_with url: statements_upload_path, multipart: true do |form|%>
    <%= form.file_field :attachments, multiple: true, direct_upload: true%>
    <%= submit_tag "Upload CSV" %>
  <% end %>

<h3>Destroy all data!</h3>
<%= link_to 'Destroy', statements_destroy_path, method: :delete, data: { confirm: 'Are you sure?' } %>

<p><%= link_to 'Posts', posts_path %></p>
<p><%= link_to 'Back to home', root_path %></p>

app/views/static_pages/home.html.erb
<h1>Rails 5.2 practice</h1>
<p>Using active storage for images and importing CSV</p>
<p><%= link_to 'Posts, to upload images', posts_path %></p>
<p><%= link_to 'Statements, to import CSV', statements_index_path %></p>